### ISSUE TITLE
JS Compat - Compound Assignment Operators

### ISSUE THREAD

**Issue by joshuaevenson** [velentir/kumu#107]
Add compound assignment operators like += -= *= /=

**Comment by monesga** [comment]
This one will be a bit tricky... I wonder if they're really needed to be honest

Since there is a simple assignment alternative which is still JS compatible

I think we're trying to do the smallest JS compatible subset for now

**Comment by joshuaevenson** [comment]
I like the idea of keeping things as small as possible. People can always use babel to get to our subset, so extra operators are likely unnecessary. I'll close this for now and we can re-open if we decide it is absolutely necessary.
