### ISSUE TITLE
JavaScript compatibility

### ISSUE THREAD

**Issue by monesga** [velentir/kumu#55]
Puff changes kumu to become more JavaScript compliant as follows

- [x] null
- [x] function
- [x] let
- [x] new
- [x] extends
- [x] logical && || !
- [x] compound assignment += -= *= /=
- [x] identity === !==
- [x] arrow functions (args) => body
- [x] Math PI min()
- [x] Date 
- [x] constructor()

**Comment by monesga** [comment]
I don';t think we need to rename it to puff... Just make kumu JS compatible :)

**Comment by monesga** [comment]
See #49 for arrow functions. Separating that one

**Comment by monesga** [comment]
We might wanna split these into individual tasks so we can farm them off... `new` will need parsing work but should be easy. I can take that one

**Comment by joshuaevenson** [comment]
I'm almost done, I can just complete these inline at this point.

**Comment by joshuaevenson** [comment]
For compound assignment see #107.

**Comment by joshuaevenson** [comment]
For Math library see #108.

**Comment by joshuaevenson** [comment]
For Date library see #109.

**Comment by joshuaevenson** [comment]
These are all completed besides work that was moved to separate tasks. Any other differences with Javascript will be opened in separate tasks as well, so closing.
