### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by monesga** [velentir/kumu#71]
- [x] make clean
- [x] make all
- [x] make test
- [x] make install
- [x] make uninstall

**Comment by toddkrabach** [comment]
Initial Makefile: https://github.com/velentir/kumu/pull/90
Add `make cov`: https://github.com/velentir/kumu/pull/91

**Comment by toddkrabach** [comment]
Add make install/uninstall: https://github.com/velentir/kumu/pull/94
